### PR TITLE
Added Linux support

### PR DESCRIPTION
**Pull request by Avasam**
Contains at least all minimal features to use AutoSplit !

Multi-monitor support is the main thing missing. Everything else are nice to have, performance improvements or support for more methods.

image

### CODE REVIEW

**Comment by Erotemic** [comment]
Are there installation instructions for this? I'm currently checking it to see if it works on my system.

**Comment by Avasam** [comment]
I'm keeping this as draft until 2.0 is out. But everything is functional except the multi-monitor support.

**Comment by Avasam** [comment]
I've updated to at least boot in WSL2/WSLg, but there's no hotkey, Capture Device or Window Selection support. Rendering it pretty useless in such an environment (which would only be for development anyway).

WSL has no virtual keyboard (/dev/uinput). Capture Device just doesn't really work to begin with anyway. Xlib returns None when trying to get the  `_NET_CLIENT_LIST_STACKING` property from the root window.

**Comment by Avasam** [comment]
GitHub doesn't wanna update the ref, closing in favor of #265

**Pull request closed without merging**
