### PR TITLE
Ignore and fail commands

### PR DESCRIPTION
**Pull request by DannySchultzDev**
Adds the ignore command {i} which pauses when over the similarity threshold and unpauses after falling back under.
Adds the fail command <1000> which skips a split if it is not found after a period of time.

First time really using python so sorry if there are some errors. I couldn't test because I couldn't figure out how to build.

### CODE REVIEW

**Comment by Avasam** [comment]
Couldn't you achieve the same as your suggested `ignore` with a {p} (pause) then {pb} (unpause below) images?

Skipping a split if no match is found within a certain time is an interesting idea. Could you elaborate upon which real world use-case you would be using that?
`<>` is also planned to be used for custom comparison.

Finally, I'd recommend basing any new feature on the [`2.0.0`](https://github.com/Toufool/Auto-Split/tree/2.0.0) branch. Simple bugfixes can go on [`dev`](https://github.com/Toufool/Auto-Split/tree/dev)

Feel free to chat with us on AutoSplit 's Discord server as well !

**Comment by DannySchultzDev** [comment]
> Couldn't you achieve the same as your suggested `ignore` with a {p} (pause) then {pb} (unpause below) images?
> 
> Skipping a split if no match is found within a certain time is an interesting idea. Could you elaborate upon which real world use-case you would be using that? `<>` is also planned to be used for custom comparison.
> 
> Finally, I'd recommend basing any new feature on the [`2.0.0`](https://github.com/Toufool/Auto-Split/tree/2.0.0) branch. Simple bugfixes can go on [`dev`](https://github.com/Toufool/Auto-Split/tree/dev)
> 
> Feel free to chat with us on AutoSplit 's Discord server as well !

The reason I am using this autosplitter currently is for Wario Land Shake It to make a loadless timer. This is because Wario Land Shake It loads faster on Wii U VC than on disk. 

While I have been using {p} and {pb} to replicate the ignore function I made, because they are 2 separate splits I cannot use loops to use them efficiently (There are 10 or so black screens per level that have to be ignored). By having an ignore flag, loops can be used to more easily cut out loading screens.

The skipping feature is incase a split is not seen after a certain period of time. In my case I hope to use it at the end of Whoopsy Desert as if a tight jump is made an extra load screen is seen that I want to cut out (basically if I fail the jump I go through a portion of the level before entering a pipe taking me to the end (1 load), if I pull off the jump I fall into a lower  portion of the level quickly (1 load) before running back some more before going through another loading screen (1 more load))

since `<>` already has a use I will go ahead and change it to something else (I will ask what could be used on the discord)

**Comment by DannySchultzDev** [comment]
I totally understand,
This was the first time I had really programmed in python so it wasn’t the
cleanest code, and I found while testing that mistakes were more harmful
because if I had to reset a room it would throw off the number of loads
present, in turn making the last few load screens not be removed. I wish
you luck with implementing general support for loading screens!

**Comment by Avasam** [comment]
As discussed, the `ignore` feature should rather be implemented by rethinking how autosplit (would) support parallel comparisons and pause-timer comparisons.

The `fail` command is an interesting idea. But would have to be split from this PR. There's going to be way too much conflicts here once 2.0 is merged anyway.
Also feel free to discuss about it on Discord, where Toufool and other users can more easily give feadback on the idea. And re-open a fresh PR.

**Pull request closed without merging**
